function [recall, precision, summary] = cfar_evaluator(dataset_root, varargin)
%CFAR_EVALUATOR Evaluate 2D CA-CFAR detector on STFT tiles.
%
%   This helper evaluates a MATLAB phased.CFARDetector2D on STFT tiles
%   stored in tiles.h5 (generated by generate_training_signal.m).
%
%   Unlike box-to-box IoU matching (used by YOLOX), this evaluator uses
%   a pixel-coverage approach more natural for per-pixel CFAR detections:
%
%   For each GT box:
%       - Count how many pixels inside the box are marked as detections.
%       - If (detected_pixels / box_area) >= CoverageThreshold, count as TP.
%       - Otherwise, count as FN.
%
%   For false positives:
%       - Find connected components (blobs) in the detection mask.
%       - A blob is an FP if it has NO overlap with ANY GT box.
%       - Blobs that touch at least one GT box are not counted as FP
%         (they contributed to TP/FN decisions above).
%
%   This avoids the fundamental mismatch between CFAR's per-pixel output
%   and YOLOX's box-based output when using IoU for matching.
%
%   High-level pipeline:
%     1) Read tile IDs from split file or user-specified list.
%     2) Preload tiles (/S_db/<id>) and GT boxes (/boxes/<id>) into memory.
%     3) For each tile:
%          - Convert dB -> linear power.
%          - Build CUT indices for valid interior region.
%          - Run CFAR: y = cfar2d(S_power, cutidx).
%          - Scatter detections into HxW binary mask.
%          - For each GT box: check pixel coverage -> TP or FN.
%          - For each detection blob: if no GT overlap -> FP.
%     4) Aggregate TP/FP/FN and report precision/recall/F1.
%
%   Optional name-value pairs:
%       'Pfa'              - Probability of false alarm (default 1e-4).
%       'GuardBandSize'    - [rows cols] guard band (default [4 4]).
%       'TrainingBandSize' - [rows cols] training band (default [16 16]).
%       'CoverageThreshold'- Fraction of GT box pixels that must be
%                            detected to count as TP (default 0.3 = 30%).
%       'MinArea'          - Minimum blob area in pixels (default 3).
%       'TileIds'          - Optional subset of tile IDs to evaluate.

p = inputParser;
addParameter(p, 'Pfa', 1e-4, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'GuardBandSize', [4 4], @(x) isnumeric(x) && numel(x) == 2);
addParameter(p, 'TrainingBandSize', [16 16], @(x) isnumeric(x) && numel(x) == 2);
addParameter(p, 'CoverageThreshold', 0.3, @(x) isnumeric(x) && isscalar(x) && x > 0 && x <= 1);
addParameter(p, 'MinArea', 3, @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'TileIds', []);
parse(p, varargin{:});
cfg = p.Results;

if isstring(dataset_root) || ischar(dataset_root)
    dataset_root = char(dataset_root);
else
    error('dataset_root must be a string or char path.');
end

h5_path = fullfile(dataset_root, 'tensors', 'tiles.h5');
splits_dir = fullfile(dataset_root, 'splits');
test_list_path = fullfile(splits_dir, 'val.txt');

if ~isfile(h5_path)
    error('HDF5 file not found: %s', h5_path);
end
if ~isfile(test_list_path)
    error('Test split file not found: %s', test_list_path);
end

if ~isempty(cfg.TileIds)
    test_ids = cfg.TileIds;
else
    test_ids = read_id_list(test_list_path);
end
n_images = numel(test_ids);
if n_images == 0
    error('Test split is empty.');
end

% ------------------------------------------------------------------
% Preload all tiles and GT boxes into memory to avoid HDF5 overhead.
%
% tiles_map: maps tile_id (char) -> S_db tile (H x W, single).
% boxes_map: maps tile_id (char) -> GT boxes (N x 4) in [x0,y0,w,h].
% We use a single low-level HDF5 file handle for fast per-tile reads.
% ------------------------------------------------------------------
tiles_map = containers.Map('KeyType','char','ValueType','any');
boxes_map = containers.Map('KeyType','char','ValueType','any');

fprintf('CFAR evaluator: preloading %d tiles into memory...\n', n_images);
preload_log_every = max(1, floor(n_images / 20));

% Open HDF5 file once for faster per-tile reads
h5_file_id = H5F.open(h5_path, 'H5F_ACC_RDONLY', 'H5P_DEFAULT');

for k = 1:n_images
    if mod(k, preload_log_every) == 0 || k == 1 || k == n_images
        fprintf('  Preload: tile %d / %d (%.1f%%%%)\n', ...
            k, n_images, 100 * k / n_images);
    end

    tile_id = strtrim(test_ids(k));
    tile_id = char(tile_id);

    % Load STFT tile (in dB) and store using low-level HDF5.
    % h5_read_dataset returns the raw dataset stored at
    %   group_path = '/S_db', dset_name = tile_id.
    s_db = h5_read_dataset(h5_file_id, '/S_db', tile_id);
    tiles_map(tile_id) = s_db;  % keep as single; convert to double later

    % Load GT boxes for this tile. Not all tiles have /boxes/<id>,
    % so use try/catch to avoid a global group scan. Missing dataset
    % is treated as "no targets in this tile".
    try
        gt_boxes = h5_read_dataset(h5_file_id, '/boxes', tile_id);
        gt_boxes = double(gt_boxes);
        if size(gt_boxes, 2) ~= 4 && size(gt_boxes, 1) == 4
            gt_boxes = gt_boxes.';
        end
    catch
        % Missing dataset => no boxes
        gt_boxes = zeros(0, 4);
    end
    boxes_map(tile_id) = gt_boxes;
end

H5F.close(h5_file_id);

fprintf('CFAR evaluator: preload done. Running CFAR on all tiles...\n');


% ------------------------------------------------------------------
% Prepare data for parallel processing
% ------------------------------------------------------------------
% Get tile dimensions from first tile (assume all tiles are same size)
first_id = char(strtrim(test_ids(1)));
first_tile = tiles_map(first_id);
[H, W] = size(first_tile);

% Compute CUT indices once (same for all tiles)
gr = cfg.GuardBandSize(1); gc = cfg.GuardBandSize(2);
tr = cfg.TrainingBandSize(1); tc = cfg.TrainingBandSize(2);

row_min = 1 + tr + gr;
row_max = H - tr - gr;
col_min = 1 + tc + gc;
col_max = W - tc - gc;

if row_min > row_max || col_min > col_max
    error('Guard + training band too large for tile size %dx%d', H, W);
end

[ccol, rrow] = meshgrid(col_min:col_max, row_min:row_max);
cutidx = [rrow(:).'; ccol(:).'];
n_cuts = size(cutidx, 2);

% Precompute linear indices for scattering detections
cut_lin_idx = sub2ind([H, W], cutidx(1, :), cutidx(2, :));

fprintf('CFAR evaluator: tile size %dx%d, %d CUT cells per tile\n', H, W, n_cuts);

% Convert Map to cell arrays for parfor slicing
tiles_cell = cell(n_images, 1);
boxes_cell = cell(n_images, 1);
for k = 1:n_images
    tile_id = char(strtrim(test_ids(k)));
    tiles_cell{k} = double(tiles_map(tile_id));
    boxes_cell{k} = boxes_map(tile_id);
end

% Clear maps to free memory
clear tiles_map boxes_map;

% ------------------------------------------------------------------
% Run CFAR + evaluation in parallel using parfor
% ------------------------------------------------------------------
% Preallocate output arrays (parfor requires fixed-size sliced outputs)
tp_arr = zeros(n_images, 1);
fp_arr = zeros(n_images, 1);
fn_arr = zeros(n_images, 1);
ngt_arr = zeros(n_images, 1);
npred_arr = zeros(n_images, 1);

% Extract config values for parfor (avoid broadcast of entire struct)
pfa = cfg.Pfa;
guard_size = cfg.GuardBandSize;
train_size = cfg.TrainingBandSize;
min_area = cfg.MinArea;
coverage_thr = cfg.CoverageThreshold;

fprintf('CFAR evaluator: running CFAR + eval on %d tiles (parfor)...\n', n_images);

t_start = tic;

parfor k = 1:n_images
    % Convert dB -> linear power
    s_db = tiles_cell{k};
    s_power = 10.^(s_db / 10.0);

    % Create CFAR detector (one per worker)
    cfar_det = phased.CFARDetector2D( ...
        'Method', 'CA', ...
        'GuardBandSize', guard_size, ...
        'TrainingBandSize', train_size, ...
        'ProbabilityFalseAlarm', pfa, ...
        'OutputFormat', 'CUT result', ...
        'ThresholdOutputPort', false);

    % Run CFAR
    y = cfar_det(s_power, cutidx);

    % Scatter to detection mask
    det_mask = false(H, W);
    det_mask(cut_lin_idx) = logical(y(:));

    % Prune small blobs
    if min_area > 1
        det_mask = bwareaopen(det_mask, round(min_area));
    end

    % Evaluate coverage
    gt_boxes = boxes_cell{k};
    [tp, fp, fn, ngt, npred] = eval_tile_coverage(det_mask, gt_boxes, coverage_thr);

    tp_arr(k) = tp;
    fp_arr(k) = fp;
    fn_arr(k) = fn;
    ngt_arr(k) = ngt;
    npred_arr(k) = npred;
end

inference_time = toc(t_start);

fprintf('CFAR evaluator: complete in %.2f seconds\n', inference_time);

% Aggregate results
total_tp = sum(tp_arr);
total_fp = sum(fp_arr);
total_fn = sum(fn_arr);
total_gt = sum(ngt_arr);
total_pred = sum(npred_arr);

precision = total_tp / (total_tp + total_fp);
if ~isfinite(precision)
    precision = 0.0;
end
recall = total_tp / (total_tp + total_fn);
if ~isfinite(recall)
    recall = 0.0;
end
if (precision + recall) > 0
    f1 = 2 * precision * recall / (precision + recall);
else
    f1 = 0.0;
end

avg_time_ms = 1000 * inference_time / n_images;

summary = sprintf([ ...
    'STFT Evaluation Results\n', ...
    '-----------------------\n', ...
    'Total GT boxes:   %d\n', ...
    'Total predictions:%d\n', ...
    'TP: %d, FP: %d, FN: %d\n', ...
    'Precision: %.4f\n', ...
    'Recall:    %.4f\n', ...
    'F1 Score:  %.4f\n', ...
    'Avg inference time: %.2f ms/image\n' ...
    ], total_gt, total_pred, total_tp, total_fp, total_fn, precision, recall, f1, avg_time_ms);

fprintf('%s\n', summary);
end


function data = h5_read_dataset(file_id, group_path, dset_name)
% Read a dataset from an open HDF5 file using low-level API.
% Mirrors the h5_write_dataset helper used in generate_training_signal.m

group_id = H5G.open(file_id, group_path);
dset_id  = H5D.open(group_id, dset_name);

data = H5D.read(dset_id, 'H5ML_DEFAULT', 'H5S_ALL', 'H5S_ALL', 'H5P_DEFAULT');

H5D.close(dset_id);
H5G.close(group_id);
end


function ids = read_id_list(path)
txt = fileread(path);
if isempty(txt)
    ids = strings(0, 1);
else
    parts = regexp(txt, '\r?\n', 'split');
    parts = parts(~cellfun('isempty', parts));
    ids = string(parts(:));
end
end


function [tp, fp, fn, n_gt, n_pred] = eval_tile_coverage(det_mask, gt_boxes, coverage_thr)
%EVAL_TILE_COVERAGE Evaluate CFAR detections using pixel-coverage approach.
%
%   For each GT box:
%       - Count detected pixels inside the box.
%       - If (detected_pixels / box_area) >= coverage_thr -> TP, else FN.
%
%   For FP:
%       - Find connected components in det_mask.
%       - A blob is FP if it has NO overlap with ANY GT box.
%
%   Inputs:
%       det_mask     - H x W logical detection mask from CFAR.
%       gt_boxes     - N x 4 GT boxes as [x0, y0, w, h], 0-based coords.
%       coverage_thr - Fraction of box area that must be detected for TP.
%
%   Outputs:
%       tp, fp, fn   - True positives, false positives, false negatives.
%       n_gt         - Number of GT boxes.
%       n_pred       - Number of detection blobs.

[H, W] = size(det_mask);

if isempty(gt_boxes)
    n_gt = 0;
else
    n_gt = size(gt_boxes, 1);
end

% Count detection blobs
cc = bwconncomp(det_mask);
n_pred = cc.NumObjects;

% Edge case: no detections and no GT
if n_pred == 0 && n_gt == 0
    tp = 0; fp = 0; fn = 0;
    return;
elseif n_pred == 0
    % No detections: all GT boxes are false negatives
    tp = 0; fp = 0; fn = n_gt;
    return;
elseif n_gt == 0
    % No GT: all detection blobs are false positives
    tp = 0; fp = n_pred; fn = 0;
    return;
end

% --- Evaluate TP/FN for each GT box based on pixel coverage ---
tp = 0;
fn = 0;

for i = 1:n_gt
    % GT box in [x0, y0, w, h] with 0-based coords
    x0 = gt_boxes(i, 1);
    y0 = gt_boxes(i, 2);
    bw = gt_boxes(i, 3);
    bh = gt_boxes(i, 4);

    % Convert to 1-based MATLAB indices and clamp to image bounds
    col_min = max(1, x0 + 1);
    col_max = min(W, x0 + bw);
    row_min = max(1, y0 + 1);
    row_max = min(H, y0 + bh);

    if row_min > row_max || col_min > col_max
        % Box is outside image bounds or degenerate
        fn = fn + 1;
        continue;
    end

    % Count detected pixels inside this GT box
    box_region = det_mask(row_min:row_max, col_min:col_max);
    detected_pixels = sum(box_region(:));
    box_area = bw * bh;

    if box_area > 0 && (detected_pixels / box_area) >= coverage_thr
        tp = tp + 1;
    else
        fn = fn + 1;
    end
end

% --- Evaluate FP: blobs with NO overlap to ANY GT box ---
% Create a mask of all GT box regions
gt_mask = false(H, W);
for i = 1:n_gt
    x0 = gt_boxes(i, 1);
    y0 = gt_boxes(i, 2);
    bw = gt_boxes(i, 3);
    bh = gt_boxes(i, 4);

    col_min = max(1, x0 + 1);
    col_max = min(W, x0 + bw);
    row_min = max(1, y0 + 1);
    row_max = min(H, y0 + bh);

    if row_min <= row_max && col_min <= col_max
        gt_mask(row_min:row_max, col_min:col_max) = true;
    end
end

% For each detection blob, check if it overlaps any GT region
fp = 0;
for j = 1:n_pred
    blob_pixels = cc.PixelIdxList{j};
    % Check if ANY pixel in this blob overlaps with ANY GT box
    if ~any(gt_mask(blob_pixels))
        % No overlap with any GT -> this is a false positive
        fp = fp + 1;
    end
end
end
