classdef stft_h5_helpers
    %% STFT_H5_HELPERS Shared HDF5 helper functions for STFT dataset loading.
    %
    % This class provides static methods for reading STFT tiles and GT boxes
    % from HDF5 files generated by generate_training_signal.m.
    %
    % HDF5 structure:
    % /S_db/<tile_id>   - STFT tiles in dB, H x W (single precision)
    % /boxes/<tile_id>  - GT boxes as [x0, y0, w, h], 0-based (int32)
    %
    % Split files:
    %     splits/train.txt, val.txt, test.txt - one tile ID per line
    %
    % Usage:
    %     ids = stft_h5_helpers.read_id_list('path/to/splits/val.txt');
    %     file_id = H5F.open('path/to/tiles.h5', 'H5F_ACC_RDONLY', 'H5P_DEFAULT');
    %     tile = stft_h5_helpers.read_tile(file_id, tile_id);
    %     boxes = stft_h5_helpers.read_boxes(file_id, tile_id);
    %     H5F.close(file_id);
    methods (Static)
        function ids = read_id_list(path)
            %% READ_ID_LIST Read tile IDs from a split file.
            %
            % ids = stft_h5_helpers.read_id_list(path)
            %
            % Reads a text file with one tile ID per line and returns
            % a string array of IDs (empty lines are skipped).

            txt = fileread(path);
            if isempty(txt)
                ids = strings(0, 1);
            else
                parts = regexp(txt, '\r?\n', 'split');
                parts = parts(~cellfun('isempty', parts));
                ids = string(parts(:));
            end
        end

        function data = read_dataset(file_id, group_path, dset_name)
            %% READ_DATASET Read a dataset from an open HDF5 file.
            %
            % data = stft_h5_helpers.read_dataset(file_id, group_path, dset_name)
            %
            % Low-level HDF5 read for a dataset at group_path/dset_name.
            % The file_id must be obtained from H5F.open().

            group_id = H5G.open(file_id, group_path);
            dset_id  = H5D.open(group_id, dset_name);

            data = H5D.read(dset_id, 'H5ML_DEFAULT', 'H5S_ALL', 'H5S_ALL', 'H5P_DEFAULT');

            H5D.close(dset_id);
            H5G.close(group_id);
        end

        function tile = read_tile(file_id, tile_id)
            %% READ_TILE Read an STFT tile from /S_db/<tile_id>.
            %
            % tile = stft_h5_helpers.read_tile(file_id, tile_id)
            %
            % Returns the tile as H x W single-precision array (in dB).

            tile_id = char(tile_id);
            tile = stft_h5_helpers.read_dataset(file_id, '/S_db', tile_id);
        end

        function boxes = read_boxes(file_id, tile_id)
            %% READ_BOXES Read GT boxes from /boxes/<tile_id>.
            %
            % boxes = stft_h5_helpers.read_boxes(file_id, tile_id)
            %
            % Returns N x 4 array of [x0, y0, w, h] boxes (0-based coords).
            % Returns empty 0x4 array if no boxes exist for this tile.

            tile_id = char(tile_id);
            try
                boxes = stft_h5_helpers.read_dataset(file_id, '/boxes', tile_id);
                boxes = double(boxes);
                % Ensure boxes are N x 4 (transpose if stored as 4 x N)
                if size(boxes, 2) ~= 4 && size(boxes, 1) == 4
                    boxes = boxes.';
                end
            catch
                % Missing dataset => no boxes for this tile
                boxes = zeros(0, 4);
            end
        end

        function [tiles_cell, boxes_cell] = preload_dataset(h5_path, tile_ids)
            %% PRELOAD_DATASET Preload all tiles and boxes into cell arrays.
            %
            % [tiles_cell, boxes_cell] = stft_h5_helpers.preload_dataset(h5_path, tile_ids)
            %
            % Loads all tiles and GT boxes into memory for fast access.
            % Returns cell arrays indexed by position in tile_ids.
            %
            % Inputs:
            %     h5_path  - Path to tiles.h5 file
            %     tile_ids - String array of tile IDs to load
            %
            % Outputs:
            %     tiles_cell - Cell array of H x W tiles (in dB, single)
            %     boxes_cell - Cell array of N x 4 GT boxes

            n_images = numel(tile_ids);
            tiles_cell = cell(n_images, 1);
            boxes_cell = cell(n_images, 1);

            log_every = max(1, floor(n_images / 20));

            fprintf('Preloading %d tiles from %s...\n', n_images, h5_path);

            file_id = H5F.open(h5_path, 'H5F_ACC_RDONLY', 'H5P_DEFAULT');

            for k = 1:n_images
                if mod(k, log_every) == 0 || k == 1 || k == n_images
                    fprintf('  Preload: %d / %d (%.1f%%%%)\n', k, n_images, 100 * k / n_images);
                end

                tile_id = strtrim(tile_ids(k));
                tiles_cell{k} = stft_h5_helpers.read_tile(file_id, tile_id);
                boxes_cell{k} = stft_h5_helpers.read_boxes(file_id, tile_id);
            end

            H5F.close(file_id);

            fprintf('Preload complete.\n');
        end
    end
end
